notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: skg
  password:
    secure: YWKFP8HRlvDk9L5lTkqeKL3argG2R9QbMdWMzQ1ouaJqf55hT8l81pQPidtvWC2G/6xaWRgm8zwF7zht39zGGMnUzZV/r6fnjUTWtUDSAfVg8DNbtN3yBSDVpNE2jnbT5DRa1lt97dLJVQEC7TZd5SFJwGUR30o08DfwlUudXTjC+OZAdzaa469EWKulYf683S6Ef36bgMSN1h+GlZg5vAcUlTxk0+iXbcIr1qlu5RzqOsHgbyiBX4rm41r3yoMG4nIHDWboOaVS3r9lgDIuMQitz/7Ne2VqH1BRcWxO97X4OfzDGREzcngTBZNUiwzft5xtQ2w63bynfb2GeRcC09qovx3/62fnTmrBQeLZ2sKrEW8aoyfLwQgtljzQ6zib94vqt5otaXJxv5MD1KYwvOIxuR6EVMjw95HL3sWRD1v6A8LN3jBjmyBJtZaVafsFtC7pJu6LB/d9JiKz+ayS1p8wK2XlJxOPf6IVmO3CpDZzbr836Y0Irigx028v0m5YFX/tEscMmbEkT/CBSuWneRWESxfrnnTxUQfG+YK0n43jtJTaqDcKy7Vx3cGMbaO+2xGd0RubaM4kRUeTfYzrLhOzt3CKjPO2jM4rGhbDfVqlg5dFwg10bapyJnMDyw38LmPgshxPzrFJJMU3eg3Chv8BILMv9h1vKo+WyqK89E0=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls

