notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: dellemcnet
  password:
    secure: IeHY63sWEwUk5ATBQPHSEHkYj+8AhfCe8ZdG9VSrUXxi4k0gS4suEKt4vFpA12RrAAzzQedkF/pz4/e82otw+LsuDUIxNx2/YoEhKYE1YIMUVqe1bLiPySTebBUw0G1QD0QCXIVR1bOu6g7ezBukVIMD+RzESTuc3cGRKUmOjQP+rvUTHQ3iZD/muTPwxz2NN6NtiTWeDw2xIb2RUCLqR3P0Wj/OBSEMDQw7zMxbBXjLq7z+o/OtTPZjXfJqVB3huVRXsBLLWCY7O7YN/KjfSaJdAins+xtq02JF+80RPTwNcoqwgDGBTaKZUOd7Cahkk0ij9K3AxZBbdMdjJyJhNUoBnRTcWCLan48flsnj/MFRZnCuoS0w1kFFDa0Ss9pBDzeFNTnw440YBzFVVJCiyJEZxOaWcfdl+GSjULDpX3gR/ekIs+mS5vtMVn8QfCHLmcr/35NP7snNjCDB3EE5CpKisWcSNRHeMtqDKSlpFuRv8Ru/ZyvLYNhxjqsEkC007oczCNqErTI1KInaTWCpRHdnwh9rpSVUMccA8fgfHyQzo3o7Og5EiNXnCVYFoEj0moS1WVkjaOZ1t1YV/KT3FNPCoyQebwsfceM9IPWqrKOJSTwHXLsVPUTHqN/joA1m2Drr3TtrFvyWtjyik5G9SkLYwoMH5+mkXYBAlVKJNn8=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
