notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: skg
  password:
    secure: B1Nqo/BgjOggzLQbp/oQxJSVRTbvnF5r5tqLAunrb/+luVnxNQT31jc6AsP/ZfH5oWgT+Zs9FMj8eilH4Z9qLsSPeEgCh82kvrkfOoxgNf/jJqQxcDnVSNhZBvOod7nokTXhaYAgei/VUm1AgdkibsQMLEGlz8WpGPQxnzueInuGuD6UdSWH3OXuxsdhrAs9mPHx/X6sMhR0UqoXmEg4WhDX1g4/XyhdKyjPdHW8ZWhrdGL8TfdjX+BXy0xhFYBpbBAQALggUuPG5xOI9bPVTSSVWPS7Cf8DIoH2lBz09j9l9fPJojIZzKrkB88i6fZd2paGCLCmzhDnbh7al86M7noGn4hHyPUbEzVW1Xq5IcMB14G2qAD0DO74cES27hpvun5h6SEJ0zj2SLD/IwsGzcJdfSjuyfrQPiKzSqyyEzv+gO1Z+YEkCQTDvufqfZh0b3J95RyduAjOMbeM5VbwVL+hDTpDeE9SgEZapJwee5N/t+ymQqC990gAswPdugkvZzCoclNgMLDXmAkg/w2eaZAHOb6KUkX2NOEu4Au5ZlkFE3aBpvQUZm+r8lwrSgK5gzQXQSkT3yf2uFb3BCjrNoNPFzBzsqnwPypIsnKuEyqmjMDu4fdT4p/Dg8w4XEW6BGrR7rQCLxe6LfIGkenbxpW/UD50GVqLVV9f1FiptbE=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
